<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Abonnements</name>
   <tag></tag>
   <elementGuidId>12e6ad7c-de53-4388-846c-7e048e35644c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/main/div/div/div/div[2]/div[2]/a[7]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>72e23121-6b00-4c34-a45c-81a6c8983bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss241</value>
      <webElementGuid>a6598b5a-1283-4fc4-840d-782a1438f319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Abonnements</value>
      <webElementGuid>36c82380-9ac9-44e4-8836-74f5cf3ee8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;layout jss132&quot;]/div[@class=&quot;jss133 jss2&quot;]/main[@class=&quot;jss134&quot;]/div[@class=&quot;MuiDrawer-root MuiDrawer-docked jss143&quot;]/div[@class=&quot;MuiPaper-root MuiDrawer-paper MuiDrawer-paperAnchorLeft jss145 MuiDrawer-paperAnchorDockedLeft MuiPaper-elevation0&quot;]/div[@class=&quot;CustomMenu MenuOpen jss203 jss207&quot;]/div[@class=&quot;jss204&quot;]/div[@class=&quot;MenuItemsContainer jss205&quot;]/a[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root jss238 jss197 MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button&quot;]/span[@class=&quot;jss241&quot;]</value>
      <webElementGuid>fc6cf85c-b20b-4b23-accd-81202c262608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div/div/div/div[2]/div[2]/a[7]/span</value>
      <webElementGuid>76958dc6-0d24-4221-8c01-ad114be34edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commandes'])[1]/following::span[2]</value>
      <webElementGuid>21a4be30-a8e5-41a4-9804-fb87b183db7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Devis open order'])[1]/following::span[4]</value>
      <webElementGuid>b6144cbc-23ea-4b93-bfc3-1d69dd6b6db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contrats cadre'])[1]/preceding::span[2]</value>
      <webElementGuid>79bada23-3d08-4443-ab45-8dfe5bed8a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plans de facturation'])[1]/preceding::span[4]</value>
      <webElementGuid>9cd3bfa9-87e0-4ae4-a2d1-59fd83b99f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Abonnements']/parent::*</value>
      <webElementGuid>a2191318-998e-4f95-ac83-8b1397b33818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[7]/span</value>
      <webElementGuid>b3799e5a-194b-4db4-bb3c-067f9f06c45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Abonnements' or . = 'Abonnements')]</value>
      <webElementGuid>2aad0807-09fe-4b44-b2b8-8dda3cbc2aae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
